gamemodes = {
    0: "None",
    2: "5v5 Blind Pick games",
    4: "5v5 Ranked Solo games",
    6: "5v5 Ranked Premade games",
    7: "Co-op vs AI games",
    8: "3v3 Normal games",
    9: "3v3 Ranked Flex games",
    14: "5v5 Draft Pick games",
    16: "5v5 Dominion Blind Pick games",
    17: "5v5 Dominion Draft Pick games",
    25: "Dominion Co-op vs AI games",
    31: "Co-op vs AI Intro Bot games",
    32: "Co-op vs AI Beginner Bot games",
    33: "Co-op vs AI Intermediate Bot games",
    41: "3v3 Ranked Team games",
    42: "5v5 Ranked Team games",
    52: "Co-op vs AI games",
    61: "5v5 Team Builder games",
    65: "5v5 ARAM games",
    67: "ARAM Co-op vs AI games",
    70: "One for All games",
    72: "1v1 Snowdown Showdown games",
    73: "2v2 Snowdown Showdown games",
    75: "6v6 Hexakill games",
    76: "Ultra Rapid Fire games",
    78: "One For All: Mirror Mode games",
    83: "Co-op vs AI Ultra Rapid Fire games",
    91: "Doom Bots Rank 1 games",
    92: "Doom Bots Rank 2 games",
    93: "Doom Bots Rank 5 games",
    96: "Ascension games",
    98: "6v6 Hexakill games",
    100: "5v5 ARAM games",
    300: "Legend of the Poro King games",
    310: "Nemesis games",
    313: "Black Market Brawlers games",
    315: "Nexus Siege games",
    317: "Definitely Not Dominion games",
    318: "ARURF games",
    325: "All Random games",
    400: "5v5 Draft Pick games",
    410: "5v5 Ranked Dynamic games",
    420: "5v5 Ranked Solo games",
    430: "5v5 Blind Pick games",
    440: "5v5 Ranked Flex games",
    450: "5v5 ARAM games",
    460: "3v3 Blind Pick games",
    470: "3v3 Ranked Flex games",
    600: "Blood Hunt Assassin games",
    610: "Dark Star: Singularity games",
    700: "Clash games",
    800: "Co-op vs. AI Intermediate Bot games",
    810: "Co-op vs. AI Intro Bot games",
    820: "Co-op vs. AI Beginner Bot games",
    830: "Co-op vs. AI Intro Bot games",
    840: "Co-op vs. AI Beginner Bot games",
    850: "Co-op vs. AI Intermediate Bot games",
    900: "URF games",
    910: "Ascension games",
    920: "Legend of the Poro King games",
    940: "Nexus Siege games",
    950: "Doom Bots Voting games",
    960: "Doom Bots Standard games",
    980: "Star Guardian Invasion: Normal games",
    990: "Star Guardian Invasion: Onslaught games",
    1000: "PROJECT: Hunters games",
    1010: "Snow ARURF games",
    1020: "One for All games",
    1030: "Odyssey Extraction: Intro games",
    1040: "Odyssey Extraction: Cadet games",
    1050: "Odyssey Extraction: Crewmember games",
    1060: "Odyssey Extraction: Captain games",
    1070: "Odyssey Extraction: Onslaught games",
    1090: "Teamfight Tactics games",
    1100: "Ranked Teamfight Tactics games",
    1110: "Teamfight Tactics Tutorial games",
    1111: "Teamfight Tactics test games",
    1200: "Nexus Blitz games",
    1300: "Nexus Blitz games",
    1400: "Ultimate Spellbook games",
    2000: "Tutorial 1",
    2010: "Tutorial 2",
    2020: "Tutorial 3",
}
